variables:
  GIT_DEPTH: 5

stages:
  - pull
  - npm
  - deploy

image: bozdoz/fabric-deployment:1.0.1

pull:
  stage: pull
  script:
    - fab gitpull
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

npm:
  stage: npm
  script:
    - fab npmci
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
    - changes:
      - package-lock.json

deploy:
  stage: deploy
  script:
    - fab npmbuild
  after_script:
    - apk add curl
    - |
      curl "https://api.cloudflare.com/client/v4/zones/$CF_ZONE/purge_cache" \
      -H "Authorization: Bearer $CF_TOKEN" \
      -H "Content-Type: application/json" \
      -d "{\"purge_everything\": true}"
  environment:
    name: production
    url: https://communitybiblechapel.ca
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
