version: '3.3'

services:
  mysql:
    image: mariadb
    volumes:
      - wp_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-whocares}

  wordpress:
    image: wordpress:php7.4
    depends_on:
      - cli
    volumes:
      - wordpress:/var/www/html
      - ./wp-content/themes:/var/www/html/wp-content/themes
    ports:
      - ${WP_PORT:-80}:80
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-whocares}

  cli:
    image: bozdoz/wordpress-initialize:2.4.0-20201102
    env_file: .env
    depends_on:
      - mysql
    volumes: 
      - wordpress:/var/www/html
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./docker-initialize.sh:/app/initialize.sh

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8086:80
  #   depends_on:
  #     - mysql
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_USER: ${MYSQL_USER:-root}
  #     PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-whocares}

volumes:
  wp_db:
  wordpress: