services:
  mysql:
    image: mariadb:11.4
    volumes:
      - wp_db:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: on-failure:3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-whocares}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}

  wordpress:
    image: wordpress:6.5-php8.2
    env_file: .env
    depends_on:
      - cli
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    ports:
      - ${WP_PORT:-80}:80
    restart: on-failure:3
    environment:
      WORDPRESS_DEBUG: ${WP_DEBUG:-false}
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}

  cli:
    image: bozdoz/wordpress-initialize:2.7.1-php8.0
    env_file: .env
    depends_on:
      - mysql
    volumes:
      - wordpress:/var/www/html
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./docker-initialize.sh:/app/initialize.sh
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8086:80
  #   depends_on:
  #     - mysql
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_USER: ${MYSQL_USER:-wordpress}
  #     PMA_PASSWORD: ${MYSQL_PASSWORD:-wordpress}

volumes:
  wp_db:
  wordpress:
